# Generated by Django 5.2.4 on 2025-07-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teamtournamentresult_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show this stream/video on the Streams & Videos page'),
        ),
    ]
